// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxfmLTHNj9P_4owmFzoma9Bc3K_vrEblw',
    appId: '1:910906576064:web:f65e1e225e91a8d8cdb125',
    messagingSenderId: '910906576064',
    projectId: 'deka15-453e4',
    authDomain: 'deka15-453e4.firebaseapp.com',
    storageBucket: 'deka15-453e4.firebasestorage.app',
    measurementId: 'G-MRPJVPBZ33',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAumlmMjn7oX94lgpZrlxE8v-EDEv_m-a0',
    appId: '1:910906576064:android:a596397cfd63db76cdb125',
    messagingSenderId: '910906576064',
    projectId: 'deka15-453e4',
    storageBucket: 'deka15-453e4.firebasestorage.app',
  );
}
